modLoader = "javafml"
loaderVersion = "[43,)"
license = "Terrarium Licence"
issueTrackerURL = "https://github.com/terrarium-earth/Chipped/issues"
[[mods]]
modId = "chipped"
version = "${version}"
displayName = "Chipped"
logoFile = "icon.png"
authors = "Alex Nijjar, CodexAdrian, Grimbop, Kekie6, Marc-IceBlade, MsRandom, ThatGravyBoat"
description = '''
Every block needs a friend!
'''

[[dependencies.chipped]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.chipped]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.chipped]]
modId = "resourcefullib"
mandatory = true
versionRange = "[${resourcefullib_version},)"
ordering = "NONE"
side = "BOTH"